# coding: utf-8

"""
    VxRail REST API

    The VxRail REST API provides a programmatic interface for performing VxRail administrative tasks. Data is available in JSON format.  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AccessConfigurationResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'account_name': 'str',
        'token_expiration': 'int'
    }

    attribute_map = {
        'account_name': 'account_name',
        'token_expiration': 'token_expiration'
    }

    def __init__(self, account_name=None, token_expiration=None):  # noqa: E501
        """AccessConfigurationResponse - a model defined in Swagger"""  # noqa: E501
        self._account_name = None
        self._token_expiration = None
        self.discriminator = None
        if account_name is not None:
            self.account_name = account_name
        if token_expiration is not None:
            self.token_expiration = token_expiration

    @property
    def account_name(self):
        """Gets the account_name of this AccessConfigurationResponse.  # noqa: E501

        Support account name.  # noqa: E501

        :return: The account_name of this AccessConfigurationResponse.  # noqa: E501
        :rtype: str
        """
        return self._account_name

    @account_name.setter
    def account_name(self, account_name):
        """Sets the account_name of this AccessConfigurationResponse.

        Support account name.  # noqa: E501

        :param account_name: The account_name of this AccessConfigurationResponse.  # noqa: E501
        :type: str
        """

        self._account_name = account_name

    @property
    def token_expiration(self):
        """Gets the token_expiration of this AccessConfigurationResponse.  # noqa: E501

        Token expiration value. This is Unix epoch value.  # noqa: E501

        :return: The token_expiration of this AccessConfigurationResponse.  # noqa: E501
        :rtype: int
        """
        return self._token_expiration

    @token_expiration.setter
    def token_expiration(self, token_expiration):
        """Sets the token_expiration of this AccessConfigurationResponse.

        Token expiration value. This is Unix epoch value.  # noqa: E501

        :param token_expiration: The token_expiration of this AccessConfigurationResponse.  # noqa: E501
        :type: int
        """

        self._token_expiration = token_expiration

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AccessConfigurationResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AccessConfigurationResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
