# coding: utf-8

"""
    VxRail REST API

    The VxRail REST API provides a programmatic interface for performing VxRail administrative tasks. Data is available in JSON format.  # noqa: E501

    OpenAPI spec version: 7.0.240
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CallhomeSettingsSpec(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'is_muted': 'bool'
    }

    attribute_map = {
        'is_muted': 'is_muted'
    }

    def __init__(self, is_muted=None):  # noqa: E501
        """CallhomeSettingsSpec - a model defined in Swagger"""  # noqa: E501
        self._is_muted = None
        self.discriminator = None
        self.is_muted = is_muted

    @property
    def is_muted(self):
        """Gets the is_muted of this CallhomeSettingsSpec.  # noqa: E501

        Whether call home mode is muted or unmuted. Supported values are true and false. True indicates that call home is muted.  # noqa: E501

        :return: The is_muted of this CallhomeSettingsSpec.  # noqa: E501
        :rtype: bool
        """
        return self._is_muted

    @is_muted.setter
    def is_muted(self, is_muted):
        """Sets the is_muted of this CallhomeSettingsSpec.

        Whether call home mode is muted or unmuted. Supported values are true and false. True indicates that call home is muted.  # noqa: E501

        :param is_muted: The is_muted of this CallhomeSettingsSpec.  # noqa: E501
        :type: bool
        """
        if is_muted is None:
            raise ValueError("Invalid value for `is_muted`, must not be `None`")  # noqa: E501

        self._is_muted = is_muted

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CallhomeSettingsSpec, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CallhomeSettingsSpec):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
