# coding: utf-8

"""
    VxRail REST API

    The VxRail REST API provides a programmatic interface for performing VxRail administrative tasks. Data is available in JSON format.  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DiscoveredNodeTeamingPolicyInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'default_load_balance_policy': 'str',
        'active': 'list[str]',
        'standby': 'list[str]'
    }

    attribute_map = {
        'default_load_balance_policy': 'default_load_balance_policy',
        'active': 'active',
        'standby': 'standby'
    }

    def __init__(self, default_load_balance_policy=None, active=None, standby=None):  # noqa: E501
        """DiscoveredNodeTeamingPolicyInfo - a model defined in Swagger"""  # noqa: E501
        self._default_load_balance_policy = None
        self._active = None
        self._standby = None
        self.discriminator = None
        if default_load_balance_policy is not None:
            self.default_load_balance_policy = default_load_balance_policy
        if active is not None:
            self.active = active
        if standby is not None:
            self.standby = standby

    @property
    def default_load_balance_policy(self):
        """Gets the default_load_balance_policy of this DiscoveredNodeTeamingPolicyInfo.  # noqa: E501


        :return: The default_load_balance_policy of this DiscoveredNodeTeamingPolicyInfo.  # noqa: E501
        :rtype: str
        """
        return self._default_load_balance_policy

    @default_load_balance_policy.setter
    def default_load_balance_policy(self, default_load_balance_policy):
        """Sets the default_load_balance_policy of this DiscoveredNodeTeamingPolicyInfo.


        :param default_load_balance_policy: The default_load_balance_policy of this DiscoveredNodeTeamingPolicyInfo.  # noqa: E501
        :type: str
        """

        self._default_load_balance_policy = default_load_balance_policy

    @property
    def active(self):
        """Gets the active of this DiscoveredNodeTeamingPolicyInfo.  # noqa: E501


        :return: The active of this DiscoveredNodeTeamingPolicyInfo.  # noqa: E501
        :rtype: list[str]
        """
        return self._active

    @active.setter
    def active(self, active):
        """Sets the active of this DiscoveredNodeTeamingPolicyInfo.


        :param active: The active of this DiscoveredNodeTeamingPolicyInfo.  # noqa: E501
        :type: list[str]
        """

        self._active = active

    @property
    def standby(self):
        """Gets the standby of this DiscoveredNodeTeamingPolicyInfo.  # noqa: E501


        :return: The standby of this DiscoveredNodeTeamingPolicyInfo.  # noqa: E501
        :rtype: list[str]
        """
        return self._standby

    @standby.setter
    def standby(self, standby):
        """Sets the standby of this DiscoveredNodeTeamingPolicyInfo.


        :param standby: The standby of this DiscoveredNodeTeamingPolicyInfo.  # noqa: E501
        :type: list[str]
        """

        self._standby = standby

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DiscoveredNodeTeamingPolicyInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DiscoveredNodeTeamingPolicyInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
