# coding: utf-8

"""
    VxRail REST API

    The VxRail REST API provides a programmatic interface for performing VxRail administrative tasks. Data is available in JSON format.  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ESAConfigSpecV7StandardKeyProvider(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'kmip_server_info': 'ESAConfigSpecV7KmipServerInfo'
    }

    attribute_map = {
        'kmip_server_info': 'kmip_server_info'
    }

    def __init__(self, kmip_server_info=None):  # noqa: E501
        """ESAConfigSpecV7StandardKeyProvider - a model defined in Swagger"""  # noqa: E501
        self._kmip_server_info = None
        self.discriminator = None
        if kmip_server_info is not None:
            self.kmip_server_info = kmip_server_info

    @property
    def kmip_server_info(self):
        """Gets the kmip_server_info of this ESAConfigSpecV7StandardKeyProvider.  # noqa: E501


        :return: The kmip_server_info of this ESAConfigSpecV7StandardKeyProvider.  # noqa: E501
        :rtype: ESAConfigSpecV7KmipServerInfo
        """
        return self._kmip_server_info

    @kmip_server_info.setter
    def kmip_server_info(self, kmip_server_info):
        """Sets the kmip_server_info of this ESAConfigSpecV7StandardKeyProvider.


        :param kmip_server_info: The kmip_server_info of this ESAConfigSpecV7StandardKeyProvider.  # noqa: E501
        :type: ESAConfigSpecV7KmipServerInfo
        """

        self._kmip_server_info = kmip_server_info

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ESAConfigSpecV7StandardKeyProvider, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ESAConfigSpecV7StandardKeyProvider):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
