# coding: utf-8

"""
    VxRail REST API

    The VxRail REST API provides a programmatic interface for performing VxRail administrative tasks. Data is available in JSON format.  # noqa: E501

    OpenAPI spec version: 7.0.350
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class EsxiHostCredential(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'sn': 'str',
        'root_user': 'User'
    }

    attribute_map = {
        'sn': 'sn',
        'root_user': 'root_user'
    }

    def __init__(self, sn=None, root_user=None):  # noqa: E501
        """EsxiHostCredential - a model defined in Swagger"""  # noqa: E501
        self._sn = None
        self._root_user = None
        self.discriminator = None
        self.sn = sn
        self.root_user = root_user

    @property
    def sn(self):
        """Gets the sn of this EsxiHostCredential.  # noqa: E501

        Serial number of the ESXi host.  # noqa: E501

        :return: The sn of this EsxiHostCredential.  # noqa: E501
        :rtype: str
        """
        return self._sn

    @sn.setter
    def sn(self, sn):
        """Sets the sn of this EsxiHostCredential.

        Serial number of the ESXi host.  # noqa: E501

        :param sn: The sn of this EsxiHostCredential.  # noqa: E501
        :type: str
        """
        if sn is None:
            raise ValueError("Invalid value for `sn`, must not be `None`")  # noqa: E501

        self._sn = sn

    @property
    def root_user(self):
        """Gets the root_user of this EsxiHostCredential.  # noqa: E501


        :return: The root_user of this EsxiHostCredential.  # noqa: E501
        :rtype: User
        """
        return self._root_user

    @root_user.setter
    def root_user(self, root_user):
        """Sets the root_user of this EsxiHostCredential.


        :param root_user: The root_user of this EsxiHostCredential.  # noqa: E501
        :type: User
        """
        if root_user is None:
            raise ValueError("Invalid value for `root_user`, must not be `None`")  # noqa: E501

        self._root_user = root_user

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EsxiHostCredential, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EsxiHostCredential):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
