# coding: utf-8

"""
    VxRail REST API

    The VxRail REST API provides a programmatic interface for performing VxRail administrative tasks. Data is available in JSON format.  # noqa: E501

    OpenAPI spec version: 7.0.240
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class HostShutdownSpec(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'dryrun': 'bool',
        'evacuate_poweredoff_vms': 'bool'
    }

    attribute_map = {
        'dryrun': 'dryrun',
        'evacuate_poweredoff_vms': 'evacuate_poweredoff_vms'
    }

    def __init__(self, dryrun=None, evacuate_poweredoff_vms=None):  # noqa: E501
        """HostShutdownSpec - a model defined in Swagger"""  # noqa: E501
        self._dryrun = None
        self._evacuate_poweredoff_vms = None
        self.discriminator = None
        self.dryrun = dryrun
        self.evacuate_poweredoff_vms = evacuate_poweredoff_vms

    @property
    def dryrun(self):
        """Gets the dryrun of this HostShutdownSpec.  # noqa: E501

        Perform a dry run to check whether it is safe to shutdown  # noqa: E501

        :return: The dryrun of this HostShutdownSpec.  # noqa: E501
        :rtype: bool
        """
        return self._dryrun

    @dryrun.setter
    def dryrun(self, dryrun):
        """Sets the dryrun of this HostShutdownSpec.

        Perform a dry run to check whether it is safe to shutdown  # noqa: E501

        :param dryrun: The dryrun of this HostShutdownSpec.  # noqa: E501
        :type: bool
        """
        if dryrun is None:
            raise ValueError("Invalid value for `dryrun`, must not be `None`")  # noqa: E501

        self._dryrun = dryrun

    @property
    def evacuate_poweredoff_vms(self):
        """Gets the evacuate_poweredoff_vms of this HostShutdownSpec.  # noqa: E501

        Evacuate powered off vms for this node  # noqa: E501

        :return: The evacuate_poweredoff_vms of this HostShutdownSpec.  # noqa: E501
        :rtype: bool
        """
        return self._evacuate_poweredoff_vms

    @evacuate_poweredoff_vms.setter
    def evacuate_poweredoff_vms(self, evacuate_poweredoff_vms):
        """Sets the evacuate_poweredoff_vms of this HostShutdownSpec.

        Evacuate powered off vms for this node  # noqa: E501

        :param evacuate_poweredoff_vms: The evacuate_poweredoff_vms of this HostShutdownSpec.  # noqa: E501
        :type: bool
        """
        if evacuate_poweredoff_vms is None:
            raise ValueError("Invalid value for `evacuate_poweredoff_vms`, must not be `None`")  # noqa: E501

        self._evacuate_poweredoff_vms = evacuate_poweredoff_vms

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(HostShutdownSpec, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HostShutdownSpec):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
