# coding: utf-8

"""
    VxRail REST API

    The VxRail REST API provides a programmatic interface for performing VxRail administrative tasks. Data is available in JSON format.  # noqa: E501

    OpenAPI spec version: 7.0.240
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class IdracNetworkSpec(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'ip': 'IdracNetworkSpecIp',
        'dhcp_enabled': 'bool',
        'vlan': 'IdracNetworkSpecVlan'
    }

    attribute_map = {
        'ip': 'ip',
        'dhcp_enabled': 'dhcp_enabled',
        'vlan': 'vlan'
    }

    def __init__(self, ip=None, dhcp_enabled=None, vlan=None):  # noqa: E501
        """IdracNetworkSpec - a model defined in Swagger"""  # noqa: E501
        self._ip = None
        self._dhcp_enabled = None
        self._vlan = None
        self.discriminator = None
        if ip is not None:
            self.ip = ip
        if dhcp_enabled is not None:
            self.dhcp_enabled = dhcp_enabled
        if vlan is not None:
            self.vlan = vlan

    @property
    def ip(self):
        """Gets the ip of this IdracNetworkSpec.  # noqa: E501


        :return: The ip of this IdracNetworkSpec.  # noqa: E501
        :rtype: IdracNetworkSpecIp
        """
        return self._ip

    @ip.setter
    def ip(self, ip):
        """Sets the ip of this IdracNetworkSpec.


        :param ip: The ip of this IdracNetworkSpec.  # noqa: E501
        :type: IdracNetworkSpecIp
        """

        self._ip = ip

    @property
    def dhcp_enabled(self):
        """Gets the dhcp_enabled of this IdracNetworkSpec.  # noqa: E501

        Whether DHCP service enabled or not  # noqa: E501

        :return: The dhcp_enabled of this IdracNetworkSpec.  # noqa: E501
        :rtype: bool
        """
        return self._dhcp_enabled

    @dhcp_enabled.setter
    def dhcp_enabled(self, dhcp_enabled):
        """Sets the dhcp_enabled of this IdracNetworkSpec.

        Whether DHCP service enabled or not  # noqa: E501

        :param dhcp_enabled: The dhcp_enabled of this IdracNetworkSpec.  # noqa: E501
        :type: bool
        """

        self._dhcp_enabled = dhcp_enabled

    @property
    def vlan(self):
        """Gets the vlan of this IdracNetworkSpec.  # noqa: E501


        :return: The vlan of this IdracNetworkSpec.  # noqa: E501
        :rtype: IdracNetworkSpecVlan
        """
        return self._vlan

    @vlan.setter
    def vlan(self, vlan):
        """Sets the vlan of this IdracNetworkSpec.


        :param vlan: The vlan of this IdracNetworkSpec.  # noqa: E501
        :type: IdracNetworkSpecVlan
        """

        self._vlan = vlan

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IdracNetworkSpec, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IdracNetworkSpec):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
