# coding: utf-8

"""
    VxRail REST API

    The VxRail REST API provides a programmatic interface for performing VxRail administrative tasks. Data is available in JSON format.  # noqa: E501

    OpenAPI spec version: 7.0.350
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse404(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'message': 'str',
        'error_code': 'float',
        'message_code': 'str'
    }

    attribute_map = {
        'message': 'message',
        'error_code': 'error_code',
        'message_code': 'message_code'
    }

    def __init__(self, message=None, error_code=None, message_code=None):  # noqa: E501
        """InlineResponse404 - a model defined in Swagger"""  # noqa: E501
        self._message = None
        self._error_code = None
        self._message_code = None
        self.discriminator = None
        if message is not None:
            self.message = message
        if error_code is not None:
            self.error_code = error_code
        if message_code is not None:
            self.message_code = message_code

    @property
    def message(self):
        """Gets the message of this InlineResponse404.  # noqa: E501


        :return: The message of this InlineResponse404.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this InlineResponse404.


        :param message: The message of this InlineResponse404.  # noqa: E501
        :type: str
        """

        self._message = message

    @property
    def error_code(self):
        """Gets the error_code of this InlineResponse404.  # noqa: E501


        :return: The error_code of this InlineResponse404.  # noqa: E501
        :rtype: float
        """
        return self._error_code

    @error_code.setter
    def error_code(self, error_code):
        """Sets the error_code of this InlineResponse404.


        :param error_code: The error_code of this InlineResponse404.  # noqa: E501
        :type: float
        """

        self._error_code = error_code

    @property
    def message_code(self):
        """Gets the message_code of this InlineResponse404.  # noqa: E501

        Reserved key. Returns an empty string always  # noqa: E501

        :return: The message_code of this InlineResponse404.  # noqa: E501
        :rtype: str
        """
        return self._message_code

    @message_code.setter
    def message_code(self, message_code):
        """Sets the message_code of this InlineResponse404.

        Reserved key. Returns an empty string always  # noqa: E501

        :param message_code: The message_code of this InlineResponse404.  # noqa: E501
        :type: str
        """

        self._message_code = message_code

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse404, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse404):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
