# coding: utf-8

"""
    VxRail REST API

    The VxRail REST API provides a programmatic interface for performing VxRail administrative tasks. Data is available in JSON format.  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from vxrail_ansible_utility.models.nic_v3 import NicV3  # noqa: F401,E501

class NicV4(NicV3):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'vendor': 'str',
        'model': 'str'
    }
    if hasattr(NicV3, "swagger_types"):
        swagger_types.update(NicV3.swagger_types)

    attribute_map = {
        'vendor': 'vendor',
        'model': 'model'
    }
    if hasattr(NicV3, "attribute_map"):
        attribute_map.update(NicV3.attribute_map)

    def __init__(self, vendor=None, model=None, *args, **kwargs):  # noqa: E501
        """NicV4 - a model defined in Swagger"""  # noqa: E501
        self._vendor = None
        self._model = None
        self.discriminator = None
        if vendor is not None:
            self.vendor = vendor
        if model is not None:
            self.model = model
        NicV3.__init__(self, *args, **kwargs)

    @property
    def vendor(self):
        """Gets the vendor of this NicV4.  # noqa: E501

        The vendor of the NIC.  # noqa: E501

        :return: The vendor of this NicV4.  # noqa: E501
        :rtype: str
        """
        return self._vendor

    @vendor.setter
    def vendor(self, vendor):
        """Sets the vendor of this NicV4.

        The vendor of the NIC.  # noqa: E501

        :param vendor: The vendor of this NicV4.  # noqa: E501
        :type: str
        """

        self._vendor = vendor

    @property
    def model(self):
        """Gets the model of this NicV4.  # noqa: E501

        The model of the NIC.  # noqa: E501

        :return: The model of this NicV4.  # noqa: E501
        :rtype: str
        """
        return self._model

    @model.setter
    def model(self, model):
        """Sets the model of this NicV4.

        The model of the NIC.  # noqa: E501

        :param model: The model of this NicV4.  # noqa: E501
        :type: str
        """

        self._model = model

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(NicV4, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NicV4):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
