# coding: utf-8

"""
    Day1 Bring Up Configuration

    The set of Day 1 Bring Up Configuration API(s) are used to deploy VxRail cluster.  # noqa: E501

    OpenAPI spec version: 7.0.240
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class SFSAuthentication(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'switch_conn_info': 'SwitchConnInfo'
    }

    attribute_map = {
        'switch_conn_info': 'switch_conn_info'
    }

    def __init__(self, switch_conn_info=None):  # noqa: E501
        """SFSAuthentication - a model defined in Swagger"""  # noqa: E501
        self._switch_conn_info = None
        self.discriminator = None
        self.switch_conn_info = switch_conn_info

    @property
    def switch_conn_info(self):
        """Gets the switch_conn_info of this SFSAuthentication.  # noqa: E501


        :return: The switch_conn_info of this SFSAuthentication.  # noqa: E501
        :rtype: SwitchConnInfo
        """
        return self._switch_conn_info

    @switch_conn_info.setter
    def switch_conn_info(self, switch_conn_info):
        """Sets the switch_conn_info of this SFSAuthentication.


        :param switch_conn_info: The switch_conn_info of this SFSAuthentication.  # noqa: E501
        :type: SwitchConnInfo
        """
        if switch_conn_info is None:
            raise ValueError("Invalid value for `switch_conn_info`, must not be `None`")  # noqa: E501

        self._switch_conn_info = switch_conn_info

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SFSAuthentication, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SFSAuthentication):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
