# coding: utf-8

"""
    VxRail REST API

    The VxRail REST API provides a programmatic interface for performing VxRail administrative tasks. Data is available in JSON format.  # noqa: E501

    OpenAPI spec version: 7.0.350
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class StaticIPSettingsSpec(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'ip': 'str',
        'gateway': 'str',
        'netmask': 'str',
        'vlan_id': 'str'
    }

    attribute_map = {
        'ip': 'ip',
        'gateway': 'gateway',
        'netmask': 'netmask',
        'vlan_id': 'vlan_id'
    }

    def __init__(self, ip=None, gateway=None, netmask=None, vlan_id=None):  # noqa: E501
        """StaticIPSettingsSpec - a model defined in Swagger"""  # noqa: E501
        self._ip = None
        self._gateway = None
        self._netmask = None
        self._vlan_id = None
        self.discriminator = None
        self.ip = ip
        self.gateway = gateway
        self.netmask = netmask
        self.vlan_id = vlan_id

    @property
    def ip(self):
        """Gets the ip of this StaticIPSettingsSpec.  # noqa: E501

        The static IP address to be set for VxRail Manager  # noqa: E501

        :return: The ip of this StaticIPSettingsSpec.  # noqa: E501
        :rtype: str
        """
        return self._ip

    @ip.setter
    def ip(self, ip):
        """Sets the ip of this StaticIPSettingsSpec.

        The static IP address to be set for VxRail Manager  # noqa: E501

        :param ip: The ip of this StaticIPSettingsSpec.  # noqa: E501
        :type: str
        """
        if ip is None:
            raise ValueError("Invalid value for `ip`, must not be `None`")  # noqa: E501

        self._ip = ip

    @property
    def gateway(self):
        """Gets the gateway of this StaticIPSettingsSpec.  # noqa: E501

        The network gateway address to be used for VxRail Manager  # noqa: E501

        :return: The gateway of this StaticIPSettingsSpec.  # noqa: E501
        :rtype: str
        """
        return self._gateway

    @gateway.setter
    def gateway(self, gateway):
        """Sets the gateway of this StaticIPSettingsSpec.

        The network gateway address to be used for VxRail Manager  # noqa: E501

        :param gateway: The gateway of this StaticIPSettingsSpec.  # noqa: E501
        :type: str
        """
        if gateway is None:
            raise ValueError("Invalid value for `gateway`, must not be `None`")  # noqa: E501

        self._gateway = gateway

    @property
    def netmask(self):
        """Gets the netmask of this StaticIPSettingsSpec.  # noqa: E501

        The subnet mask to be used for VxRail Manager  # noqa: E501

        :return: The netmask of this StaticIPSettingsSpec.  # noqa: E501
        :rtype: str
        """
        return self._netmask

    @netmask.setter
    def netmask(self, netmask):
        """Sets the netmask of this StaticIPSettingsSpec.

        The subnet mask to be used for VxRail Manager  # noqa: E501

        :param netmask: The netmask of this StaticIPSettingsSpec.  # noqa: E501
        :type: str
        """
        if netmask is None:
            raise ValueError("Invalid value for `netmask`, must not be `None`")  # noqa: E501

        self._netmask = netmask

    @property
    def vlan_id(self):
        """Gets the vlan_id of this StaticIPSettingsSpec.  # noqa: E501

        The VLAN ID to be used for VxRail Manager  # noqa: E501

        :return: The vlan_id of this StaticIPSettingsSpec.  # noqa: E501
        :rtype: str
        """
        return self._vlan_id

    @vlan_id.setter
    def vlan_id(self, vlan_id):
        """Sets the vlan_id of this StaticIPSettingsSpec.

        The VLAN ID to be used for VxRail Manager  # noqa: E501

        :param vlan_id: The vlan_id of this StaticIPSettingsSpec.  # noqa: E501
        :type: str
        """
        if vlan_id is None:
            raise ValueError("Invalid value for `vlan_id`, must not be `None`")  # noqa: E501

        self._vlan_id = vlan_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(StaticIPSettingsSpec, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StaticIPSettingsSpec):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
