# coding: utf-8

"""
    VxRail REST API

    The VxRail REST API provides a programmatic interface for performing VxRail administrative tasks. Data is available in JSON format.  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SystemInitSpecV5VxrailManagedWitnessNode(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'witness_vm': 'SystemInitSpecV5VxrailManagedWitnessNodeWitnessVm',
        'witness_sled': 'SystemInitVxMWitnessNodeV7WitnessSled'
    }

    attribute_map = {
        'witness_vm': 'witness_vm',
        'witness_sled': 'witness_sled'
    }

    def __init__(self, witness_vm=None, witness_sled=None):  # noqa: E501
        """SystemInitSpecV5VxrailManagedWitnessNode - a model defined in Swagger"""  # noqa: E501
        self._witness_vm = None
        self._witness_sled = None
        self.discriminator = None
        if witness_vm is not None:
            self.witness_vm = witness_vm
        if witness_sled is not None:
            self.witness_sled = witness_sled

    @property
    def witness_vm(self):
        """Gets the witness_vm of this SystemInitSpecV5VxrailManagedWitnessNode.  # noqa: E501


        :return: The witness_vm of this SystemInitSpecV5VxrailManagedWitnessNode.  # noqa: E501
        :rtype: SystemInitSpecV5VxrailManagedWitnessNodeWitnessVm
        """
        return self._witness_vm

    @witness_vm.setter
    def witness_vm(self, witness_vm):
        """Sets the witness_vm of this SystemInitSpecV5VxrailManagedWitnessNode.


        :param witness_vm: The witness_vm of this SystemInitSpecV5VxrailManagedWitnessNode.  # noqa: E501
        :type: SystemInitSpecV5VxrailManagedWitnessNodeWitnessVm
        """

        self._witness_vm = witness_vm

    @property
    def witness_sled(self):
        """Gets the witness_sled of this SystemInitSpecV5VxrailManagedWitnessNode.  # noqa: E501


        :return: The witness_sled of this SystemInitSpecV5VxrailManagedWitnessNode.  # noqa: E501
        :rtype: SystemInitVxMWitnessNodeV7WitnessSled
        """
        return self._witness_sled

    @witness_sled.setter
    def witness_sled(self, witness_sled):
        """Sets the witness_sled of this SystemInitSpecV5VxrailManagedWitnessNode.


        :param witness_sled: The witness_sled of this SystemInitSpecV5VxrailManagedWitnessNode.  # noqa: E501
        :type: SystemInitVxMWitnessNodeV7WitnessSled
        """

        self._witness_sled = witness_sled

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SystemInitSpecV5VxrailManagedWitnessNode, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SystemInitSpecV5VxrailManagedWitnessNode):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
