# coding: utf-8

"""
    VxRail REST API

    The VxRail REST API provides a programmatic interface for performing VxRail administrative tasks. Data is available in JSON format.  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SystemInitStorageV7EncryptionDataAtRestKmipServerInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'address': 'str',
        'port': 'int'
    }

    attribute_map = {
        'name': 'name',
        'address': 'address',
        'port': 'port'
    }

    def __init__(self, name=None, address=None, port=None):  # noqa: E501
        """SystemInitStorageV7EncryptionDataAtRestKmipServerInfo - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._address = None
        self._port = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if address is not None:
            self.address = address
        if port is not None:
            self.port = port

    @property
    def name(self):
        """Gets the name of this SystemInitStorageV7EncryptionDataAtRestKmipServerInfo.  # noqa: E501

        The KMS server name  # noqa: E501

        :return: The name of this SystemInitStorageV7EncryptionDataAtRestKmipServerInfo.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SystemInitStorageV7EncryptionDataAtRestKmipServerInfo.

        The KMS server name  # noqa: E501

        :param name: The name of this SystemInitStorageV7EncryptionDataAtRestKmipServerInfo.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def address(self):
        """Gets the address of this SystemInitStorageV7EncryptionDataAtRestKmipServerInfo.  # noqa: E501

        The KMS server IP or FQDN  # noqa: E501

        :return: The address of this SystemInitStorageV7EncryptionDataAtRestKmipServerInfo.  # noqa: E501
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this SystemInitStorageV7EncryptionDataAtRestKmipServerInfo.

        The KMS server IP or FQDN  # noqa: E501

        :param address: The address of this SystemInitStorageV7EncryptionDataAtRestKmipServerInfo.  # noqa: E501
        :type: str
        """

        self._address = address

    @property
    def port(self):
        """Gets the port of this SystemInitStorageV7EncryptionDataAtRestKmipServerInfo.  # noqa: E501

        The KMS server port number  # noqa: E501

        :return: The port of this SystemInitStorageV7EncryptionDataAtRestKmipServerInfo.  # noqa: E501
        :rtype: int
        """
        return self._port

    @port.setter
    def port(self, port):
        """Sets the port of this SystemInitStorageV7EncryptionDataAtRestKmipServerInfo.

        The KMS server port number  # noqa: E501

        :param port: The port of this SystemInitStorageV7EncryptionDataAtRestKmipServerInfo.  # noqa: E501
        :type: int
        """

        self._port = port

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SystemInitStorageV7EncryptionDataAtRestKmipServerInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SystemInitStorageV7EncryptionDataAtRestKmipServerInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
